name: Deploy Angular app to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if different
      - master  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'  # Specify the Node.js version

      - name: Install dependencies
        run: |
          npm install
          npm install ts-node
          npm install dotenv

      - name: Build project
        run: npm run build --prod -- --base-href="/brief-generation-poc/"

      - name: Create CNAME file
        run: echo 'www.briefforge.com' > ./dist/brief-generation-poc/CNAME

      - name: Deploy to GitHub Pages
        run: |
          npm install -g gh-pages
          gh-pages -d dist/brief-generation-poc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
